# Generated by Django 4.2.7 on 2025-07-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.CharField(blank=True, choices=[('ATENDENTE', 'Atendente'), ('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('COORDENADOR', 'Coordenador')], max_length=20),
        ),
    ]
