# Generated by Django 4.2.7 on 2025-07-29 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_user_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='uploads/prontuarios/%Y/%m/%d/')),
                ('hash_arquivo', models.CharField(blank=True, max_length=64)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios', to='clinica.atendimento')),
                ('coordenador', models.ForeignKey(limit_choices_to={'perfil': 'COORDENADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prontuarios_coordenador', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios', to='clinica.paciente')),
                ('professor', models.ForeignKey(limit_choices_to={'perfil': 'PROFESSOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
            },
        ),
    ]
