# Generated by Django 5.2.4 on 2025-07-29 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_prontuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='clinica.clinica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='clinica.clinica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prontuario',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios', to='clinica.clinica'),
            preserve_default=False,
        ),
    ]
