# Generated by Django 4.2.7 on 2025-07-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_agendamento_clinica_paciente_clinica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='prontuario',
            name='clinica',
        ),
    ]
